### ISSUE TITLE
Update for Rails 5

### ISSUE THREAD

**Issue by NorCalDavid** [plataformatec/mail_form#45] opened 2016-06-17 17:57 UTC
Can you tell me if this gem will be updated to work with Rails 5.  It currently works but is causing some issues, I believe because it injects relationships on ActiveRecord::Base rather than ApplicationRecord.

**Comment by marvindanig** [comment] 2016-06-22 13:41
+1 ... I hope this gem is updated for new rails.

**Comment by lucasmazza** [comment] 2016-06-22 19:05
We haven't used mail form in quite a bit and currently we don't have any plans on working on the upgrade, but we are open to any patches and contributions to upgrade the gem to Rails 5 and we can grant commit/release access for those who want to do further maintenance work on it.

**Comment by king601** [comment] 2016-06-29 04:14
@NorCalDavid Could you give any steps to reproduce the errors? I just threw Rails 5 and mail_form together and made a simple contact form work. I was going to take a stab at reproducing/attempting to upgrade it but I didn't run into any errors.

**Comment by NorCalDavid** [comment] 2016-07-01 22:00
The only time the error occurs is when you attempt to create and migrate the DB after mail_form is installed.  If you comment out mail_form in you model and remove it from your gemfile you can create and migrate then add it back.

It seems to work fine otherwise.  Interestingly enough, it has now stopped working on a rails 4 app.  Digging into that issue now.

**Comment by king601** [comment] 2016-07-01 22:08
I did run into some problems upgrading an app of mine from 4.2 to 5 last night due to the gemspec dependencies specifying it to be < 5, so I forked it and bumped them on mine. 

I hadn't used mail_form for that case, but if I can find the time I'll try and poke around and see what I can see

**Comment by stuwil** [comment] 2016-07-06 02:27
Opened #46 for Rails 5 support. Tests are passing, and I couldn't reproduce any errors when using an ActiveRecord model. @NorCalDavid, can you please try the PR, or provide more details on the error you're seeing?

**Comment by nashby** [comment] 2016-10-22 17:08
Tested master branch with Rails 5 and it works good. Thanks guys, closing this. @lucasmazza maybe it's time to release a new version?

**Closed by nashby** 2016-10-22 17:08 UTC

**Comment by lucasmazza** [comment] 2016-10-31 15:50
@nashby released 1.6.0 :+1:
